### ISSUE TITLE
Fail to run Jasmine meteor npm run test:watch

### ISSUE THREAD

**Issue by FelipeMiranda** [Urigo/meteor-angular-socially#138]
$ meteor npm run test:watch

> socially@ test:watch /Users/felipe/Projects/socially
> meteor test --driver-package sanjo:jasmine

sh: meteor: command not found

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/felipe/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/felipe/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "run" "test:watch"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! socially@ test:watch: `meteor test --driver-package sanjo:jasmine`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the socially@ test:watch script 'meteor test --driver-package sanjo:jasmine'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the socially package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor test --driver-package sanjo:jasmine
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socially
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls socially
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/felipe/Projects/socially/npm-debug.log

**Comment by DAB0mB** [comment]
@FelipeMiranda You probably hit the watchers limit. Each Linux OS has a limit of how many files can be watched by the user. To raise that limit run the following command

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

Tell me if it did the trick for you

**Comment by bengyles** [comment]
I have this problem on my Windows machine too. I tried updating node to the newest version but it's still the same error:

C:\Users\Ben\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: EPERM: operation not permitted, symlink 'C:\Users\Ben\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os.windows.x86_32\dev_bundle\server-lib\node_module
s\' -> 'C:\Users\Ben\AppData\Local\Temp\meteor-test-run1gq0ah3\.meteor\local\build\programs\server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1586:35)
    at Object.files.cp_r (C:\tools\fs\files.js:515:11)
    at C:\tools\fs\files.js:502:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:489:25)
    at C:\tools\fs\files.js:502:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:489:25)
    at C:\tools\fs\files.js:502:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:489:25)
    at copyDirIntoTestRunnerApp (C:\tools\cli\commands.js:1697:15)
    at doTestCommand (C:\tools\cli\commands.js:1703:5)
    at Command.func (C:\tools\cli\commands.js:1538:10)
    at C:\tools\cli\main.js:1483:23
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socially-demo@ test:watch: `meteor test --driver-package sanjo:jasmine`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socially-demo@ test:watch script 'meteor test --driver-package sanjo:jasmine'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the socially-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor test --driver-package sanjo:jasmine
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socially-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls socially-demo
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ben\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os.windows.x86_32\dev_bundle\.npm\_logs\2017-05-22T15_31_54_226Z-debug.log
